"""Add expanded Islamic finance modules

Revision ID: 4a903cf1e441
Revises: c2875af72292
Create Date: 2026-04-25 15:30:44.192776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a903cf1e441'
down_revision: Union[str, Sequence[str], None] = 'c2875af72292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ijarah_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('asset_description', sa.String(), nullable=False),
    sa.Column('asset_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('lease_term_months', sa.Integer(), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_lease_to_own', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'TERMINATED', name='ijarahstatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ijarah_contracts_customer_id'), 'ijarah_contracts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ijarah_contracts_id'), 'ijarah_contracts', ['id'], unique=False)
    op.create_table('mudaraba_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.String(), nullable=False),
    sa.Column('manager_id', sa.String(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('investor_profit_ratio', sa.Float(), nullable=False),
    sa.Column('manager_profit_ratio', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSAL', 'ACTIVE', 'LIQUIDATED', 'TERMINATED', name='mudarabastatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mudaraba_contracts_id'), 'mudaraba_contracts', ['id'], unique=False)
    op.create_index(op.f('ix_mudaraba_contracts_investor_id'), 'mudaraba_contracts', ['investor_id'], unique=False)
    op.create_index(op.f('ix_mudaraba_contracts_manager_id'), 'mudaraba_contracts', ['manager_id'], unique=False)
    op.create_table('musharaka_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musharaka_type', sa.Enum('PERMANENT', 'DIMINISHING', name='musharakatype'), nullable=False),
    sa.Column('total_capital', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('asset_description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISSOLVED', name='musharakastatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_musharaka_contracts_id'), 'musharaka_contracts', ['id'], unique=False)
    op.create_table('zakat_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('zakat_base', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('zakat_due', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('nisab_value_at_time', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zakat_calculations_customer_id'), 'zakat_calculations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_zakat_calculations_id'), 'zakat_calculations', ['id'], unique=False)
    op.create_table('mudaraba_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('investor_share', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('manager_share', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('distribution_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['mudaraba_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mudaraba_distributions_id'), 'mudaraba_distributions', ['id'], unique=False)
    op.create_table('musharaka_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('capital_contribution', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('equity_percentage', sa.Float(), nullable=False),
    sa.Column('profit_share_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['musharaka_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_musharaka_partners_id'), 'musharaka_partners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_musharaka_partners_id'), table_name='musharaka_partners')
    op.drop_table('musharaka_partners')
    op.drop_index(op.f('ix_mudaraba_distributions_id'), table_name='mudaraba_distributions')
    op.drop_table('mudaraba_distributions')
    op.drop_index(op.f('ix_zakat_calculations_id'), table_name='zakat_calculations')
    op.drop_index(op.f('ix_zakat_calculations_customer_id'), table_name='zakat_calculations')
    op.drop_table('zakat_calculations')
    op.drop_index(op.f('ix_musharaka_contracts_id'), table_name='musharaka_contracts')
    op.drop_table('musharaka_contracts')
    op.drop_index(op.f('ix_mudaraba_contracts_manager_id'), table_name='mudaraba_contracts')
    op.drop_index(op.f('ix_mudaraba_contracts_investor_id'), table_name='mudaraba_contracts')
    op.drop_index(op.f('ix_mudaraba_contracts_id'), table_name='mudaraba_contracts')
    op.drop_table('mudaraba_contracts')
    op.drop_index(op.f('ix_ijarah_contracts_id'), table_name='ijarah_contracts')
    op.drop_index(op.f('ix_ijarah_contracts_customer_id'), table_name='ijarah_contracts')
    op.drop_table('ijarah_contracts')
    # ### end Alembic commands ###
