"""Initial migration

Revision ID: c2875af72292
Revises: 
Create Date: 2026-04-25 14:03:36.950473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2875af72292'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('murabaha_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('CONSUMER_GOODS', 'VEHICLE', 'REAL_ESTATE', 'COMMODITY', name='assettype'), nullable=False),
    sa.Column('asset_description', sa.String(), nullable=False),
    sa.Column('asset_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bank_markup', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_financing_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_disclosed', sa.Boolean(), nullable=False),
    sa.Column('markup_disclosed', sa.Boolean(), nullable=False),
    sa.Column('asset_owned_by_bank', sa.Boolean(), nullable=False),
    sa.Column('bank_purchase_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sale_contract_timestamp', sa.DateTime(), nullable=True),
    sa.Column('fatwa_reference', sa.String(), nullable=False),
    sa.Column('sharia_sequence_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'CUSTOMER_ACCEPTED', 'BANK_PURCHASED', 'SOLD_TO_CUSTOMER', 'ACTIVE', 'COMPLETED', 'DEFAULTED', name='contractstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_murabaha_contracts_customer_id'), 'murabaha_contracts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_murabaha_contracts_id'), 'murabaha_contracts', ['id'], unique=False)
    op.create_table('takaful_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'DEFICIT', name='poolstatus'), nullable=False),
    sa.Column('total_funds', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_takaful_pools_id'), 'takaful_pools', ['id'], unique=False)
    op.create_table('murabaha_ownership_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('VENDOR_TO_BANK', 'BANK_TO_CUSTOMER', name='eventtype'), nullable=False),
    sa.Column('transfer_proof_reference', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['murabaha_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_murabaha_ownership_events_id'), 'murabaha_ownership_events', ['id'], unique=False)
    op.create_table('murabaha_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('principal_portion', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('profit_portion', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'LATE', name='paymentstatus'), nullable=False),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['murabaha_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_murabaha_payments_id'), 'murabaha_payments', ['id'], unique=False)
    op.create_table('murabaha_sharia_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.String(), nullable=False),
    sa.Column('audit_date', sa.DateTime(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['murabaha_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_murabaha_sharia_audits_id'), 'murabaha_sharia_audits', ['id'], unique=False)
    op.create_table('takaful_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('coverage_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='policystatus'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['takaful_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_takaful_policies_customer_id'), 'takaful_policies', ['customer_id'], unique=False)
    op.create_index(op.f('ix_takaful_policies_id'), 'takaful_policies', ['id'], unique=False)
    op.create_table('murabaha_charity_obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('late_fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('is_donated', sa.Boolean(), nullable=False),
    sa.Column('donation_date', sa.DateTime(), nullable=True),
    sa.Column('charity_receipt_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['murabaha_contracts.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['murabaha_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_murabaha_charity_obligations_id'), 'murabaha_charity_obligations', ['id'], unique=False)
    op.create_table('murabaha_profit_recognition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('deferred_profit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('realized_profit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recognition_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['murabaha_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_murabaha_profit_recognition_id'), 'murabaha_profit_recognition', ['id'], unique=False)
    op.create_table('takaful_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_approved', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('incident_description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'PAID', name='claimstatus'), nullable=False),
    sa.Column('submitted_date', sa.DateTime(), nullable=False),
    sa.Column('resolved_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['takaful_policies.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['takaful_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_takaful_claims_id'), 'takaful_claims', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_takaful_claims_id'), table_name='takaful_claims')
    op.drop_table('takaful_claims')
    op.drop_index(op.f('ix_murabaha_profit_recognition_id'), table_name='murabaha_profit_recognition')
    op.drop_table('murabaha_profit_recognition')
    op.drop_index(op.f('ix_murabaha_charity_obligations_id'), table_name='murabaha_charity_obligations')
    op.drop_table('murabaha_charity_obligations')
    op.drop_index(op.f('ix_takaful_policies_id'), table_name='takaful_policies')
    op.drop_index(op.f('ix_takaful_policies_customer_id'), table_name='takaful_policies')
    op.drop_table('takaful_policies')
    op.drop_index(op.f('ix_murabaha_sharia_audits_id'), table_name='murabaha_sharia_audits')
    op.drop_table('murabaha_sharia_audits')
    op.drop_index(op.f('ix_murabaha_payments_id'), table_name='murabaha_payments')
    op.drop_table('murabaha_payments')
    op.drop_index(op.f('ix_murabaha_ownership_events_id'), table_name='murabaha_ownership_events')
    op.drop_table('murabaha_ownership_events')
    op.drop_index(op.f('ix_takaful_pools_id'), table_name='takaful_pools')
    op.drop_table('takaful_pools')
    op.drop_index(op.f('ix_murabaha_contracts_id'), table_name='murabaha_contracts')
    op.drop_index(op.f('ix_murabaha_contracts_customer_id'), table_name='murabaha_contracts')
    op.drop_table('murabaha_contracts')
    # ### end Alembic commands ###
